#!/usr/bin/python3
"""
    Module that use with SQLAlchemy's ORM
    to facilitate interactions of the class with states
    table in dedicated database, allowing CRUD
    actions on state records
"""

from sqlalchemy import Column, Integer, String
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship

Base = declarative_base()


class State(Base):
    """
    Class that represents a state in the states table
    of hbtn_0e_6_usa database

    Attributes:
        id (int): Unique id for the sate, autogenerated
                and set as primary key, cannot be NUll
        name (str): name of the stated, cannot be NULL
    """
    __tablename__ = 'states'

    id = Column(Integer, primary_key=True, autoincrement=True, nullable=False)
    name = Column(String(128), nullable=False)

    cities = relationship("City", back_populates="state")